### ISSUE TITLE
VariationalDeconvnet does not work for continuous case 

### ISSUE THREAD

**Issue by zencoding** [y0ast/VariationalDeconvnet#2]
Hi,
    I am having been playing with VariationalDeconvet but unable to get it working for Continuous case.  I used the CIFAR10 dataset and immediately ran into issues since the GuassianCriterion requires two input (mu and log(sigma_square)).  I used the continuous file from VAE project as an reference and adapted it to run on continuous dataset, specifically I added the concat and parallel modules to get the two required outputs.  

I am getting the outputs without any issues but when I ran the encoder output (z coding) into a logistic regression (based on similar work in projectAI) I get bad loss typically around 1.7

Upon reviewing the main.lua file, I noticed some discrepancies, I am not sure if these are bugs or may be I don't understand something subtle, 

1) function getLowerbound(data) -  

Lowerbound in the paper is defined as -KLD + log (pxz) and the objective of VA is to maximize this value.  The negation of err (forward pass of GuassianCriterion) in this function (line 81) seems incorrect, should this be positive then the lowerbound = err - KLD will be correct

2) function opfunc 
In this function, it seems that we are minimizing the negative lowerbound hence we have 

-lowerbound = -(err - KLD) = -err + KLD

but the derivate (df_dw) is also negated, I am not sure about this step since this will lead to ascent in rmsprop and not descent.  

Thank you for you help

**Comment by y0ast** [comment]
Hi! You are right, this doesn't work for the continuous case. Unfortunately the code got a bit messy with the minus signs, refer to the implementation for the continuous case here: https://github.com/y0ast/VAE-Torch/blob/master/continuousva.lua

This is just a project, not really a reference implementation.
